#!/bin/sh
# Build Stage
FROM python:3.12.1 AS builder
WORKDIR /code
ADD . /code
RUN pip install httpx
RUN pip install pyinstaller
RUN pyinstaller -F ./refresh.py

# Runtime
FROM ubuntu:22.04 AS runtime
WORKDIR /app
COPY --from=builder /code/dist/refresh .
ENTRYPOINT ["./refresh"]